export interface Product {
  id: string
  name: string
  category: string
  subcategory: string
  description: string
  price: number
  originalPrice?: number
  images: string[]
  variants: {
    tier?: string
    shape?: string
    color?: string
    size?: string
  }
  specifications: {
    material?: string
    dimensions?: string
    weight?: string
    features?: string[]
  }
  inStock: boolean
  featured?: boolean
}

export const products: Product[] = [
  // Category 1: Multipurpose Storage Basket (NEW)
  {
    id: "msb-2t-sq",
    name: "2 Tier Multipurpose Storage Basket - Square",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description:
      "Versatile 2-tier square storage basket perfect for organizing any space. Durable construction with modern design.",
    price: 1299,
    originalPrice: 1599,
    images: [
      "https://m.media-amazon.com/images/I/61XTgguf9kL.jpg",
      "https://m.media-amazon.com/images/I/51qdEScHECL.jpg",
      "https://m.media-amazon.com/images/I/51aYNIMDPoL.jpg",
      "https://m.media-amazon.com/images/I/61P4ixSkhiL.jpg",
      "https://m.media-amazon.com/images/I/51-ZVJwmseL.jpg"
    ],
    variants: { tier: "2 Tier", shape: "Square" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "30cm x 30cm x 45cm",
      weight: "2.5kg",
      features: ["Easy Assembly", "Rust Resistant", "Multi-purpose Use"],
    },
    inStock: true,
    featured: true,
  },
  {
    id: "msb-2t-rd",
    name: "2 Tier Multipurpose Storage Basket - Round",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Elegant 2-tier round storage basket with space-saving design. Perfect for modern homes.",
    price: 1399,
    originalPrice: 1699,
    images: [
      "https://m.media-amazon.com/images/I/61VDCDMvTvL.jpg",
      "https://m.media-amazon.com/images/I/51+Grppbe2L.jpg",
      "https://m.media-amazon.com/images/I/61O7Ob2C9wL.jpg",
      "https://m.media-amazon.com/images/I/619QU2X2hKL.jpg",
      "https://m.media-amazon.com/images/I/516qV+NLEkL.jpg"
    ],
    variants: { tier: "2 Tier", shape: "Round" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "32cm diameter x 45cm height",
      weight: "2.3kg",
      features: ["Easy Assembly", "Rust Resistant", "Space Saving"],
    },
    inStock: true,
  },
  {
    id: "msb-3t-sq",
    name: "3 Tier Multipurpose Storage Basket - Square",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Spacious 3-tier square storage solution for maximum organization efficiency.",
    price: 1799,
    originalPrice: 2199,
    images: [
      "https://m.media-amazon.com/images/I/61ZP5+IbzTL.jpg",
      "https://m.media-amazon.com/images/I/61ZyXXu9ZfL.jpg",
      "https://m.media-amazon.com/images/I/51VlC-3qQpL.jpg",
      "https://m.media-amazon.com/images/I/61P0cYL97NL.jpg",
      "https://m.media-amazon.com/images/I/51Y6c-ve0CL.jpg"

      ],
    variants: { tier: "3 Tier", shape: "Square" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "30cm x 30cm x 65cm",
      weight: "3.2kg",
      features: ["Easy Assembly", "Rust Resistant", "High Capacity"],
    },
    inStock: true,
    featured: true,
  },
  {
    id: "msb-3t-rd",
    name: "3 Tier Multipurpose Storage Basket - Round",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Stylish 3-tier round storage basket combining functionality with aesthetic appeal.",
    price: 1899,
    images: ["https://m.media-amazon.com/images/I/61awPmKco4L.jpg",
      "https://m.media-amazon.com/images/I/51Y9QCqsS7L.jpg",
      "https://m.media-amazon.com/images/I/61Wq96lgfQL.jpg",
      "https://m.media-amazon.com/images/I/61WOY5Ldx2L.jpg",
      "https://m.media-amazon.com/images/I/519lyeYZIcL.jpg"
    ],
    variants: { tier: "3 Tier", shape: "Round" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "32cm diameter x 65cm height",
      weight: "3.0kg",
      features: ["Easy Assembly", "Rust Resistant", "Elegant Design"],
    },
    inStock: true,
  },
  {
    id: "msb-4t-sq",
    name: "4 Tier Multipurpose Storage Basket - Square",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Extra-large 4-tier square storage basket for maximum organization capacity.",
    price: 2299,
    originalPrice: 2799,
    images: [
      "https://m.media-amazon.com/images/I/61iKwlWWuJL.jpg",
      "https://m.media-amazon.com/images/I/61iKwlWWuJL.jpg",
      "https://m.media-amazon.com/images/I/51k0FHY9nDL.jpg",
      "https://m.media-amazon.com/images/I/61u-CQ+3dCL.jpg",
      "https://m.media-amazon.com/images/I/51fex8tszKL.jpg"
    ],
    variants: { tier: "4 Tier", shape: "Square" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "30cm x 30cm x 85cm",
      weight: "4.0kg",
      features: ["Easy Assembly", "Rust Resistant", "Maximum Storage"],
    },
    inStock: true,
  },
  {
    id: "msb-4t-rd",
    name: "4 Tier Multipurpose Storage Basket - Round",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Premium 4-tier round storage basket with elegant design and superior capacity.",
    price: 2399,
    images: ["https://m.media-amazon.com/images/I/61QmGIGaujL.jpg",
      "https://m.media-amazon.com/images/I/51dTC0GzqBL.jpg",
      "https://m.media-amazon.com/images/I/51PglOjBmhL.jpg",
      "https://m.media-amazon.com/images/I/61Ob2DV5OGL.jpg",
      "https://m.media-amazon.com/images/I/51KbemWZc1L.jpg"

    ],
    variants: { tier: "4 Tier", shape: "Round" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "32cm diameter x 85cm height",
      weight: "3.8kg",
      features: ["Easy Assembly", "Rust Resistant", "Premium Design"],
    },
    inStock: true,
  },
  {
    id: "msb-5t-sq",
    name: "5 Tier Multipurpose Storage Basket - Square",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Ultimate 5-tier square storage solution for professional organization needs.",
    price: 2799,
    originalPrice: 3299,
    images: [
      "https://m.media-amazon.com/images/I/61T0n+27-WL.jpg",
      "https://m.media-amazon.com/images/I/51ewqe7Zo8L.jpg",
      "https://m.media-amazon.com/images/I/61SlEwB7XzL.jpg",
      "https://m.media-amazon.com/images/I/61PWKXhOsFL.jpg",
      "https://m.media-amazon.com/images/I/51VgLLv9q9L.jpg"
    ],
    variants: { tier: "5 Tier", shape: "Square" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "30cm x 30cm x 105cm",
      weight: "4.8kg",
      features: ["Easy Assembly", "Rust Resistant", "Ultimate Storage"],
    },
    inStock: true,
    featured: true,
  },
  {
    id: "msb-5t-rd",
    name: "5 Tier Multipurpose Storage Basket - Round",
    category: "Storage Baskets",
    subcategory: "Multipurpose Storage Basket",
    description: "Top-tier 5-level round storage basket for comprehensive organization solutions.",
    price: 2899,
    images: ["https://m.media-amazon.com/images/I/51htkSFixnL.jpg",
      "https://m.media-amazon.com/images/I/51jUi5RmvvL.jpg",
      "https://m.media-amazon.com/images/I/51GhM1eHTRL.jpg",
      "https://m.media-amazon.com/images/I/611M94mf-mL.jpg",
      "https://m.media-amazon.com/images/I/51GkZsC2zWL.jpg"
    ],
    variants: { tier: "5 Tier", shape: "Round" },
    specifications: {
      material: "Premium Steel with Powder Coating",
      dimensions: "32cm diameter x 105cm height",
      weight: "4.6kg",
      features: ["Easy Assembly", "Rust Resistant", "Professional Grade"],
    },
    inStock: true,
  },

  // Category 2: Kitchen Storage Rack
  {
    id: "ksr-2t-bk",
    name: "2 Tier Kitchen Storage Rack - Black",
    category: "Kitchen Storage",
    subcategory: "Kitchen Storage Rack",
    description: "Compact 2-tier black kitchen storage rack perfect for small spaces and essential organization.",
    price: 1299,
    originalPrice: 1599,
    images: ["/placeholder.svg?height=400&width=400&text=2+Tier+Kitchen+Rack+Black"],
    variants: { tier: "2 Tier", color: "Black" },
    specifications: {
      material: "Stainless Steel with Black Coating",
      dimensions: "45cm x 25cm x 40cm",
      weight: "2.8kg",
      features: ["Water Resistant", "Easy Clean", "Compact Design"],
    },
    inStock: true,
  },
  {
    id: "ksr-2t-wh",
    name: "2 Tier Kitchen Storage Rack - White",
    category: "Kitchen Storage",
    subcategory: "Kitchen Storage Rack",
    description: "Sleek 2-tier white kitchen storage rack with modern aesthetics and practical functionality.",
    price: 1299,
    originalPrice: 1599,
    images: ["/placeholder.svg?height=400&width=400&text=2+Tier+Kitchen+Rack+White"],
    variants: { tier: "2 Tier", color: "White" },
    specifications: {
      material: "Stainless Steel with White Coating",
      dimensions: "45cm x 25cm x 40cm",
      weight: "2.8kg",
      features: ["Water Resistant", "Easy Clean", "Modern Look"],
    },
    inStock: true,
  },
  {
    id: "ksr-3t-bk",
    name: "3 Tier Kitchen Storage Rack - Black",
    category: "Kitchen Storage",
    subcategory: "Kitchen Storage Rack",
    description: "Sleek black 3-tier kitchen storage rack for organizing utensils, spices, and cookware.",
    price: 1599,
    originalPrice: 1899,
    images: ["/placeholder.svg?height=400&width=400&text=3+Tier+Kitchen+Rack+Black"],
    variants: { tier: "3 Tier", color: "Black" },
    specifications: {
      material: "Stainless Steel with Black Coating",
      dimensions: "45cm x 25cm x 60cm",
      weight: "3.5kg",
      features: ["Water Resistant", "Easy Clean", "Stable Base"],
    },
    inStock: true,
    featured: true,
  },
  {
    id: "ksr-3t-wh",
    name: "3 Tier Kitchen Storage Rack - White",
    category: "Kitchen Storage",
    subcategory: "Kitchen Storage Rack",
    description: "Clean white 3-tier kitchen storage rack that complements any kitchen decor.",
    price: 1599,
    originalPrice: 1899,
    images: ["/placeholder.svg?height=400&width=400&text=3+Tier+Kitchen+Rack+White"],
    variants: { tier: "3 Tier", color: "White" },
    specifications: {
      material: "Stainless Steel with White Coating",
      dimensions: "45cm x 25cm x 60cm",
      weight: "3.5kg",
      features: ["Water Resistant", "Easy Clean", "Modern Design"],
    },
    inStock: true,
  },

  // Category 3: Single Inverter Trolley
  {
    id: "sit-bk",
    name: "Single Inverter Trolley - Black",
    category: "Trolleys & Stands",
    subcategory: "Single Inverter Trolley",
    description: "Sturdy single inverter trolley with wheels for easy mobility. Perfect for home and office use.",
    price: 2299,
    images: ["https://m.media-amazon.com/images/I/61S49mGCbjL._SL1409_.jpg",
      "https://m.media-amazon.com/images/I/61lA4iuOA0L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61N+zcfrW1L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61qvhlDxOSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/617p7Ac+hdL._SL1500_.jpg"
    ],
    variants: { color: "Black" },
    specifications: {
      material: "Heavy Duty Steel Frame",
      dimensions: "50cm x 35cm x 75cm",
      weight: "8kg",
      features: ["360° Wheels", "Cable Management", "Adjustable Shelf"],
    },
    inStock: true,
  },
  {
    id: "sit-wh",
    name: "Single Inverter Trolley - White",
    category: "Trolleys & Stands",
    subcategory: "Single Inverter Trolley",
    description: "Professional white single inverter trolley with premium finish and smooth mobility.",
    price: 2299,
    images: ["https://m.media-amazon.com/images/I/61jYQdZwOrL._SL1221_.jpg",
      "https://m.media-amazon.com/images/I/61NBUdXZV1L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/617MO1c2xXL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/617MO1c2xXL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61KmpktRwGL._SL1500_.jpg"
    ],
    variants: { color: "White" },
    specifications: {
      material: "Heavy Duty Steel Frame",
      dimensions: "50cm x 35cm x 75cm",
      weight: "8kg",
      features: ["360° Wheels", "Cable Management", "Premium Finish"],
    },
    inStock: true,
    featured: true,
  },

  {
    id: "dit-bk",
    name: "Double Inverter Trolley - Black",
    category: "Trolleys & Stands",
    subcategory: "Double Inverter Trolley",
    description: "Heavy-duty double inverter trolley with enhanced capacity and stability for professional use.",
    price: 3299,
    originalPrice: 3799,
    images: ["https://m.media-amazon.com/images/I/61sIa7IJquL._SL1024_.jpg",
      "https://m.media-amazon.com/images/I/61o+Q0zW-FL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ExQWWo+NL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ShG3bUSQL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61vXIg47YpL._SL1500_.jpg"
    ],
    variants: { color: "Black" },
    specifications: {
      material: "Heavy Duty Steel Frame",
      dimensions: "60cm x 45cm x 80cm",
      weight: "12kg",
      features: ["360° Wheels", "Cable Management", "Double Capacity", "Reinforced Frame"],
    },
    inStock: true,
  },
  {
    id: "dit-wh",
    name: "Double Inverter Trolley - White",
    category: "Trolleys & Stands",
    subcategory: "Double Inverter Trolley",
    description: "Premium white double inverter trolley with superior build quality and professional aesthetics.",
    price: 3299,
    originalPrice: 3799,
    images: ["https://m.media-amazon.com/images/I/61KrZADPHUL._SL1024_.jpg",
      "https://m.media-amazon.com/images/I/61bbpaMnOsL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61TIIUn4nrL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61mk43WHBhL._SL1500_.jpg"
    ],
    variants: { color: "White" },
    specifications: {
      material: "Heavy Duty Steel Frame",
      dimensions: "60cm x 45cm x 80cm",
      weight: "12kg",
      features: ["360° Wheels", "Cable Management", "Double Capacity", "Premium Finish"],
    },
    inStock: true,
    featured: true,
  },

  // Category 5: Microwave Stand
  {
    id: "ms-2t-bk",
    name: "2 Tier Microwave Stand - Black",
    category: "Kitchen Storage",
    subcategory: "Microwave Stand",
    description: "Compact 2-tier microwave stand with additional storage space. Perfect for small kitchens.",
    price: 1899,
    images: ["/placeholder.svg?height=400&width=400&text=2+Tier+Microwave+Stand+Black"],
    variants: { tier: "2 Tier", color: "Black" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "60cm x 40cm x 85cm",
      weight: "12kg",
      features: ["Heat Resistant Top", "Storage Compartment", "Stable Design"],
    },
    inStock: true,
  },
  {
    id: "ms-2t-wh",
    name: "2 Tier Microwave Stand - White",
    category: "Kitchen Storage",
    subcategory: "Microwave Stand",
    description: "Clean 2-tier white microwave stand with modern design and practical storage solutions.",
    price: 1899,
    images: ["/placeholder.svg?height=400&width=400&text=2+Tier+Microwave+Stand+White"],
    variants: { tier: "2 Tier", color: "White" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "60cm x 40cm x 85cm",
      weight: "12kg",
      features: ["Heat Resistant Top", "Storage Compartment", "Modern Design"],
    },
    inStock: true,
  },
  {
    id: "ms-2t-gd",
    name: "2 Tier Microwave Stand - Golden",
    category: "Kitchen Storage",
    subcategory: "Microwave Stand",
    description: "Elegant 2-tier golden microwave stand with premium finish and sophisticated appeal.",
    price: 2199,
    originalPrice: 2599,
    images: ["/placeholder.svg?height=400&width=400&text=2+Tier+Microwave+Stand+Golden"],
    variants: { tier: "2 Tier", color: "Golden" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "60cm x 40cm x 85cm",
      weight: "12kg",
      features: ["Heat Resistant Top", "Storage Compartment", "Premium Finish"],
    },
    inStock: true,
  },
  {
    id: "ms-3t-bk",
    name: "3 Tier Microwave Stand - Black",
    category: "Kitchen Storage",
    subcategory: "Microwave Stand",
    description: "Spacious 3-tier black microwave stand with ample storage for kitchen appliances and accessories.",
    price: 2399,
    images: ["/placeholder.svg?height=400&width=400&text=3+Tier+Microwave+Stand+Black"],
    variants: { tier: "3 Tier", color: "Black" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "60cm x 40cm x 105cm",
      weight: "15kg",
      features: ["Heat Resistant Top", "Multiple Shelves", "Stable Design"],
    },
    inStock: true,
  },
  {
    id: "ms-3t-wh",
    name: "3 Tier Microwave Stand - White",
    category: "Kitchen Storage",
    subcategory: "Microwave Stand",
    description: "Versatile 3-tier white microwave stand with clean lines and maximum storage capacity.",
    price: 2399,
    images: ["/placeholder.svg?height=400&width=400&text=3+Tier+Microwave+Stand+White"],
    variants: { tier: "3 Tier", color: "White" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "60cm x 40cm x 105cm",
      weight: "15kg",
      features: ["Heat Resistant Top", "Multiple Shelves", "Modern Look"],
    },
    inStock: true,
  },
  {
    id: "ms-3t-gd",
    name: "3 Tier Microwave Stand - Golden",
    category: "Kitchen Storage",
    subcategory: "Microwave Stand",
    description: "Premium 3-tier microwave stand in elegant golden finish with ample storage.",
    price: 2599,
    originalPrice: 2999,
    images: ["/placeholder.svg?height=400&width=400&text=3+Tier+Microwave+Stand+Golden"],
    variants: { tier: "3 Tier", color: "Golden" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "60cm x 40cm x 105cm",
      weight: "15kg",
      features: ["Heat Resistant Top", "Multiple Shelves", "Premium Finish"],
    },
    inStock: true,
    featured: true,
  },

  {
    id: "ps-3t-bk",
    name: "3 Tier Printer Stand - Black",
    category: "Trolleys & Stands",
    subcategory: "Printer Stand",
    description: "Professional 3-tier black printer stand with dedicated storage for office equipment and supplies.",
    price: 2199,
    originalPrice: 2599,
    images: ["https://m.media-amazon.com/images/I/71TdE2EPZpL._SL1318_.jpg",
      "https://m.media-amazon.com/images/I/51d-ByG2OiL.jpg",
      "https://m.media-amazon.com/images/I/61uF+C2tKvL.jpg",
      "https://m.media-amazon.com/images/I/51Fdc86L0ZL.jpg",

      "https://m.media-amazon.com/images/I/51E5tCkalbL.jpg"
    ],
    variants: { tier: "3 Tier", color: "Black" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "55cm x 35cm x 90cm",
      weight: "10kg",
      features: ["Cable Management", "Paper Storage", "Stable Platform"],
    },
    inStock: true,
  },
  {
    id: "ps-3t-wh",
    name: "3 Tier Printer Stand - White",
    category: "Trolleys & Stands",
    subcategory: "Printer Stand",
    description: "Clean 3-tier white printer stand with modern design perfect for home and office environments.",
    price: 2199,
    originalPrice: 2599,
    images: ["https://m.media-amazon.com/images/I/71TSq1kdJoL._SL1332_.jpg",
      "https://m.media-amazon.com/images/I/51ef5Z6UzcL.jpg",
      "https://m.media-amazon.com/images/I/515pBXhEcIL.jpg",
      "https://m.media-amazon.com/images/I/51nps1nSWlL.jpg",
      "https://m.media-amazon.com/images/I/51bfnxJjG6L.jpg"
    ],
    variants: { tier: "3 Tier", color: "White" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "55cm x 35cm x 90cm",
      weight: "10kg",
      features: ["Cable Management", "Paper Storage", "Modern Design"],
    },
    inStock: true,
  },
  {
    id: "ps-3t-gd",
    name: "3 Tier Printer Stand - Golden",
    category: "Trolleys & Stands",
    subcategory: "Printer Stand",
    description: "Elegant 3-tier golden printer stand with premium finish for sophisticated office spaces.",
    price: 2499,
    originalPrice: 2899,
    images: ["https://m.media-amazon.com/images/I/41uq6fL+92L.jpg",
      "https://m.media-amazon.com/images/I/51D03LKPjxL.jpg",
      "https://m.media-amazon.com/images/I/513ZKLWCYyL.jpg",
      "https://m.media-amazon.com/images/I/51BRlI8HOGL.jpg",
      "https://m.media-amazon.com/images/I/51YCEjsBndL.jpg"
    ],
    variants: { tier: "3 Tier", color: "Golden" },
    specifications: {
      material: "Engineered Wood with Steel Frame",
      dimensions: "55cm x 35cm x 90cm",
      weight: "10kg",
      features: ["Cable Management", "Paper Storage", "Premium Finish"],
    },
    inStock: true,
    featured: true,
  },

  // Category 7: Umbrella Stand
  {
    id: "us-bk",
    name: "Umbrella Stand - Black",
    category: "Accessories",
    subcategory: "Umbrella Stand",
    description: "Stylish black umbrella stand with water collection tray. Perfect for entryways.",
    price: 899,
    images: ["https://m.media-amazon.com/images/I/71gLvtr2xRL._SL1339_.jpg",
      "https://m.media-amazon.com/images/I/61WQycrT4QL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61TAvHiBXiL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/616thIX230L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61hDbIXYpQL._SL1500_.jpg"
    ],
    variants: { color: "Black" },
    specifications: {
      material: "Steel with Powder Coating",
      dimensions: "25cm x 25cm x 50cm",
      weight: "2kg",
      features: ["Water Tray", "Compact Design", "Non-slip Base"],
    },
    inStock: true,
  },
  {
    id: "us-wh",
    name: "Umbrella Stand - White",
    category: "Accessories",
    subcategory: "Umbrella Stand",
    description: "Clean white umbrella stand with minimalist design and practical water collection system.",
    price: 899,
    images: ["https://m.media-amazon.com/images/I/61pnBs0SrSL._SL1024_.jpg",
      "https://m.media-amazon.com/images/I/61szXAFJn1L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61l7XjxE+uL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61hTZ2CON6L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61oRb4rCmIL._SL1500_.jpg "
    ],
    variants: { color: "White" },
    specifications: {
      material: "Steel with Powder Coating",
      dimensions: "25cm x 25cm x 50cm",
      weight: "2kg",
      features: ["Water Tray", "Minimalist Design", "Non-slip Base"],
    },
    inStock: true,
  },
  {
    id: "us-gd",
    name: "Umbrella Stand - Golden",
    category: "Accessories",
    subcategory: "Umbrella Stand",
    description: "Elegant golden umbrella stand that adds a touch of luxury to your entrance.",
    price: 1199,
    images: ["https://m.media-amazon.com/images/I/71xwViKjPvL._SL1345_.jpg",
      "https://m.media-amazon.com/images/I/61wZ2S19sZL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Xhkq2J2YL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/612TlZuDQFL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/614X6pEPbYL._SL1500_.jpg"
    ],
    variants: { color: "Golden" },
    specifications: {
      material: "Steel with Golden Finish",
      dimensions: "25cm x 25cm x 50cm",
      weight: "2.2kg",
      features: ["Water Tray", "Premium Finish", "Decorative Design"],
    },
    inStock: true,
  },

  // Category 8: Basket - Wooden Type
  {
    id: "bw-sq",
    name: "Wooden Type Basket - Square",
    category: "Storage Baskets",
    subcategory: "Wooden Type Basket",
    description: "Natural wooden square basket with rustic charm. Perfect for home decor and storage.",
    price: 799,
    images: ["/placeholder.svg?height=400&width=400&text=Wooden+Square+Basket"],
    variants: { shape: "Square" },
    specifications: {
      material: "Natural Wood with Protective Coating",
      dimensions: "30cm x 30cm x 20cm",
      weight: "1.5kg",
      features: ["Eco-friendly", "Handcrafted", "Natural Finish"],
    },
    inStock: true,
  },
  {
    id: "bw-ov",
    name: "Wooden Type Basket - Oval",
    category: "Storage Baskets",
    subcategory: "Wooden Type Basket",
    description: "Elegant oval wooden basket with smooth finish. Ideal for organizing and decoration.",
    price: 849,
    images: ["/placeholder.svg?height=400&width=400&text=Wooden+Oval+Basket"],
    variants: { shape: "Oval" },
    specifications: {
      material: "Natural Wood with Protective Coating",
      dimensions: "35cm x 25cm x 18cm",
      weight: "1.3kg",
      features: ["Eco-friendly", "Smooth Finish", "Versatile Use"],
    },
    inStock: true,
  },
  {
    id: "bw-rd",
    name: "Wooden Type Basket - Round",
    category: "Storage Baskets",
    subcategory: "Wooden Type Basket",
    description: "Classic round wooden basket with traditional craftsmanship and timeless appeal.",
    price: 799,
    images: ["/placeholder.svg?height=400&width=400&text=Wooden+Round+Basket"],
    variants: { shape: "Round" },
    specifications: {
      material: "Natural Wood with Protective Coating",
      dimensions: "30cm diameter x 20cm height",
      weight: "1.4kg",
      features: ["Eco-friendly", "Traditional Craft", "Classic Design"],
    },
    inStock: true,
  },

  {
    id: "mmsb-sq-bk",
    name: "Metal Mesh Storage Basket - Square Depth (Black)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Deep square metal mesh basket in black finish for versatile storage solutions.",
    price: 699,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Square+Black"],
    variants: { shape: "Square", color: "Black" },
    specifications: {
      material: "Steel Mesh with Black Coating",
      dimensions: "25cm x 25cm x 15cm",
      weight: "0.8kg",
      features: ["Ventilated Design", "Easy Clean", "Stackable"],
    },
    inStock: true,
  },
  {
    id: "mmsb-sq-wh",
    name: "Metal Mesh Storage Basket - Square Depth (White)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Deep square metal mesh basket in white finish with modern aesthetic appeal.",
    price: 699,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Square+White"],
    variants: { shape: "Square", color: "White" },
    specifications: {
      material: "Steel Mesh with White Coating",
      dimensions: "25cm x 25cm x 15cm",
      weight: "0.8kg",
      features: ["Ventilated Design", "Easy Clean", "Modern Look"],
    },
    inStock: true,
  },
  {
    id: "mmsb-rect-bk",
    name: "Metal Mesh Storage Basket - Rectangle (Black)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Rectangular metal mesh basket in black for efficient space utilization and organization.",
    price: 749,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Rectangle+Black"],
    variants: { shape: "Rectangle", color: "Black" },
    specifications: {
      material: "Steel Mesh with Black Coating",
      dimensions: "35cm x 20cm x 12cm",
      weight: "0.9kg",
      features: ["Ventilated Design", "Space Efficient", "Durable"],
    },
    inStock: true,
  },
  {
    id: "mmsb-rect-wh",
    name: "Metal Mesh Storage Basket - Rectangle (White)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Rectangular white metal mesh basket with clean lines and practical functionality.",
    price: 749,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Rectangle+White"],
    variants: { shape: "Rectangle", color: "White" },
    specifications: {
      material: "Steel Mesh with White Coating",
      dimensions: "35cm x 20cm x 12cm",
      weight: "0.9kg",
      features: ["Ventilated Design", "Clean Design", "Practical"],
    },
    inStock: true,
  },
  {
    id: "mmsb-sq-wh-bk",
    name: "Metal Mesh Storage Basket - Square with Wooden Handle (Black)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Square metal mesh basket in black with elegant wooden handles for easy carrying.",
    price: 899,
    originalPrice: 1099,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Square+Wood+Handle+Black"],
    variants: { shape: "Square", color: "Black" },
    specifications: {
      material: "Steel Mesh with Black Coating, Wooden Handles",
      dimensions: "25cm x 25cm x 15cm",
      weight: "1.0kg",
      features: ["Wooden Handles", "Ventilated Design", "Premium Feel"],
    },
    inStock: true,
    featured: true,
  },
  {
    id: "mmsb-sq-wh-wh",
    name: "Metal Mesh Storage Basket - Square with Wooden Handle (White)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Square white metal mesh basket with natural wooden handles combining style and function.",
    price: 899,
    originalPrice: 1099,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Square+Wood+Handle+White"],
    variants: { shape: "Square", color: "White" },
    specifications: {
      material: "Steel Mesh with White Coating, Wooden Handles",
      dimensions: "25cm x 25cm x 15cm",
      weight: "1.0kg",
      features: ["Wooden Handles", "Ventilated Design", "Stylish"],
    },
    inStock: true,
  },
  {
    id: "mmsb-rect-wh-bk",
    name: "Metal Mesh Storage Basket - Rectangle with Wooden Handle (Black)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description: "Rectangular black metal mesh basket with wooden handles for enhanced portability and style.",
    price: 949,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Rectangle+Wood+Handle+Black"],
    variants: { shape: "Rectangle", color: "Black" },
    specifications: {
      material: "Steel Mesh with Black Coating, Wooden Handles",
      dimensions: "35cm x 20cm x 12cm",
      weight: "1.1kg",
      features: ["Wooden Handles", "Portable Design", "Elegant"],
    },
    inStock: true,
  },
  {
    id: "mmsb-rect-wh-wh",
    name: "Metal Mesh Storage Basket - Rectangle with Wooden Handle (White)",
    category: "Storage Baskets",
    subcategory: "Metal Mesh Storage Basket",
    description:
      "Rectangular white metal mesh basket with wooden handles offering premium aesthetics and functionality.",
    price: 949,
    images: ["/placeholder.svg?height=400&width=400&text=Metal+Mesh+Rectangle+Wood+Handle+White"],
    variants: { shape: "Rectangle", color: "White" },
    specifications: {
      material: "Steel Mesh with White Coating, Wooden Handles",
      dimensions: "35cm x 20cm x 12cm",
      weight: "1.1kg",
      features: ["Wooden Handles", "Premium Look", "Functional"],
    },
    inStock: true,
  },

  // Category 10: TV Screen Protector
  {
    id: "tsp-24",
    name: "TV Screen Protector - 24 inch",
    category: "Accessories",
    subcategory: "TV Screen Protector",
    description: "24-inch tempered glass TV screen protector ideal for smaller displays and monitors.",
    price: 999,
    originalPrice: 1299,
    images: ["https://m.media-amazon.com/images/I/61z7+I+DCjL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61CtoBjdbSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QeEbsq9sL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X0iU4aNyL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61McKwRvH-L._SL1000_.jpg"
    ],
    variants: { size: '24"' },
    specifications: {
      material: "Tempered Glass",
      dimensions: "24 inch diagonal",
      features: ["9H Hardness", "Scratch Resistance", "Waterproof", "Crystal Clear"],
    },
    inStock: true,
  },
  {
    id: "tsp-32",
    name: "TV Screen Protector - 32 inch",
    category: "Accessories",
    subcategory: "TV Screen Protector",
    description: "32-inch tempered glass TV screen protector with 9H hardness and crystal clear visibility.",
    price: 1499,
    images: ["https://m.media-amazon.com/images/I/61z7+I+DCjL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61CtoBjdbSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QeEbsq9sL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X0iU4aNyL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61McKwRvH-L._SL1000_.jpg"
    ],
    variants: { size: '32"' },
    specifications: {
      material: "Tempered Glass",
      dimensions: "32 inch diagonal",
      features: ["9H Hardness", "Scratch Resistance", "Waterproof", "Crystal Clear"],
    },
    inStock: true,
  },
  {
    id: "tsp-43",
    name: "TV Screen Protector - 43 inch",
    category: "Accessories",
    subcategory: "TV Screen Protector",
    description: "43-inch premium tempered glass screen protector offering maximum protection for your TV.",
    price: 2199,
    images:["https://m.media-amazon.com/images/I/61z7+I+DCjL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61CtoBjdbSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QeEbsq9sL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X0iU4aNyL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61McKwRvH-L._SL1000_.jpg"
    ],
    variants: { size: '43"' },
    specifications: {
      material: "Tempered Glass",
      dimensions: "43 inch diagonal",
      features: ["9H Hardness", "Scratch Resistance", "Waterproof", "Crystal Clear"],
    },
    inStock: true,
    featured: true,
  },
  {
    id: "tsp-50",
    name: "TV Screen Protector - 50 inch",
    category: "Accessories",
    subcategory: "TV Screen Protector",
    description: "50-inch large format TV screen protector with advanced protection and clarity features.",
    price: 2999,
    originalPrice: 3499,
    images: ["https://m.media-amazon.com/images/I/61z7+I+DCjL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61CtoBjdbSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QeEbsq9sL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X0iU4aNyL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61McKwRvH-L._SL1000_.jpg"
    ],
    variants: { size: '50"' },
    specifications: {
      material: "Tempered Glass",
      dimensions: "50 inch diagonal",
      features: ["9H Hardness", "Scratch Resistance", "Waterproof", "Crystal Clear"],
    },
    inStock: true,
  },
  {
    id: "tsp-65",
    name: "TV Screen Protector - 65 inch",
    category: "Accessories",
    subcategory: "TV Screen Protector",
    description: "65-inch large format TV screen protector with advanced protection technology.",
    price: 3999,
    originalPrice: 4499,
    images: ["https://m.media-amazon.com/images/I/61z7+I+DCjL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61CtoBjdbSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QeEbsq9sL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X0iU4aNyL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61McKwRvH-L._SL1000_.jpg"
    ],
    variants: { size: '65"' },
    specifications: {
      material: "Tempered Glass",
      dimensions: "65 inch diagonal",
      features: ["9H Hardness", "Scratch Resistance", "Waterproof", "Crystal Clear"],
    },
    inStock: true,
  },
  {
    id: "tsp-75",
    name: "TV Screen Protector - 75 inch",
    category: "Accessories",
    subcategory: "TV Screen Protector",
    description: "75-inch extra-large TV screen protector for premium displays with maximum protection coverage.",
    price: 5499,
    originalPrice: 6299,
    images:["https://m.media-amazon.com/images/I/61z7+I+DCjL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61CtoBjdbSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71QeEbsq9sL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X0iU4aNyL._SL1080_.jpg",
      "https://m.media-amazon.com/images/I/61McKwRvH-L._SL1000_.jpg"
    ],
    variants: { size: '75"' },
    specifications: {
      material: "Tempered Glass",
      dimensions: "75 inch diagonal",
      features: ["9H Hardness", "Scratch Resistance", "Waterproof", "Crystal Clear"],
    },
    inStock: true,
    featured: true,
  },
]

export const categories = [
  {
    id: "storage-baskets",
    name: "Storage Baskets",
    description: "Multi-tier and specialty storage baskets for every need",
    image: "/modern-storage-baskets-organized-home.png",
  },
  {
    id: "kitchen-storage",
    name: "Kitchen Storage",
    description: "Kitchen organization solutions and appliance stands",
    image: "/kitchen-storage-racks-modern-organized.png",
  },
  {
    id: "trolleys",
    name: "Trolleys & Stands",
    description: "Mobile storage and equipment trolleys",
    image: "/modern-trolleys-and-stands-home-organization.png",
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Complete your organization with essential accessories",
    image: "/home-organization-accessories-modern-clean.png",
  },
]

// Helper functions
export function getProductsByCategory(categoryId: string): Product[] {
  const categoryMap: { [key: string]: string } = {
    "storage-baskets": "Storage Baskets",
    "kitchen-storage": "Kitchen Storage",
    trolleys: "Trolleys & Stands",
    accessories: "Accessories",
  }

  const categoryName = categoryMap[categoryId]
  return products.filter((product) => product.category === categoryName)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured).slice(0, 8)
}

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      product.subcategory.toLowerCase().includes(lowercaseQuery),
  )
}
